// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZSgAwkYfcuMA5fk35nzLM-TDinpM148A',
    appId: '1:489891881913:web:134d60291dc2a0f3a10c68',
    messagingSenderId: '489891881913',
    projectId: 'blog-web-app-3b2e5',
    authDomain: 'blog-web-app-3b2e5.firebaseapp.com',
    storageBucket: 'blog-web-app-3b2e5.appspot.com',
    measurementId: 'G-NKC0DB9H4J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDn1ObXMCDQW4QtFxYnOyfKRuosE8TXWF0',
    appId: '1:489891881913:android:99cea4b4ae50944da10c68',
    messagingSenderId: '489891881913',
    projectId: 'blog-web-app-3b2e5',
    storageBucket: 'blog-web-app-3b2e5.appspot.com',
  );
}
